"""Léxico simples PT-BR para scoring de sentimento de notícias (MVP).

Palavras em minúsculas e sem acento (a normalização em
news_sentiment_analyzer.py remove acentos antes de comparar). Expansível
livremente — não há necessidade de mudar a lógica do analyzer para adicionar
palavras novas.
"""

POSITIVE_WORDS: set[str] = {
    "alta",
    "aumento",
    "aumentou",
    "avanco",
    "avancou",
    "bateu",
    "beneficio",
    "boa",
    "bom",
    "compra",
    "confianca",
    "crescimento",
    "cresceu",
    "destaque",
    "dispara",
    "disparou",
    "expansao",
    "forte",
    "ganho",
    "ganhos",
    "lucro",
    "lucros",
    "melhora",
    "melhorou",
    "otimismo",
    "otimista",
    "positiva",
    "positivo",
    "recorde",
    "recuperacao",
    "subida",
    "subiu",
    "sucesso",
    "superavit",
    "supera",
    "superou",
    "valorizacao",
    "valorizou",
}

NEGATIVE_WORDS: set[str] = {
    "baixa",
    "cai",
    "caiu",
    "corte",
    "crise",
    "declinio",
    "deficit",
    "demissao",
    "demissoes",
    "desaceleracao",
    "desafio",
    "desconfianca",
    "despencou",
    "divida",
    "dividas",
    "fraca",
    "fraco",
    "fraude",
    "incerteza",
    "investigacao",
    "negativa",
    "negativo",
    "pessimismo",
    "pessimista",
    "perda",
    "perdas",
    "prejuizo",
    "prejuizos",
    "processo",
    "queda",
    "recessao",
    "reducao",
    "risco",
    "ruim",
    "tombou",
}
